site_name: pgEdge pg-healthcheck

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search

theme:
  name: material
  custom_dir: docs/overrides
  favicon: img/favicon.ico

  logo_dark_mode: 'img/logo-dark.png'
  logo_light_mode: 'img/logo-light.png'

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  generator: false

copyright: Copyright &copy; 2025 - 2026 pgEdge, Inc
repo_url: https://github.com/ahsanhadi/pg-healthcheck

nav:
  - Getting Started:
      - Introduction: index.md
      - Architecture: architecture.md
      - Installation: getting_started.md
  - Configuration:
      - Configuration Reference: configuration.md
  - Using pg-healthcheck:
      - CLI Usage and Modes: usage.md
      - Check Groups Reference: check_reference.md
      - JSON Output: json_output.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md
  - License: LICENSE.md
